{
 "title": "Ergo oracle",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ergo_oracle_pool_is_healthy" }
   ]
  },
  {
   "title": "Active oracle count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ergo_oracle_active_oracle_count"
    }
   ]
  },
  {
   "title": "Min required oracle count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ergo_oracle_required_oracle_count"
    }
   ]
  },
  {
   "title": "Total oracle tokens minted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ergo_oracle_total_oracle_count" }
   ]
  },
  {
   "title": "Pool box height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ergo_oracle_pool_box_height" }
   ]
  },
  {
   "title": "Reward token amount in the pool box",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ergo_oracle_pool_box_reward_token_amount"
    }
   ]
  },
  {
   "title": "Rate in pool box",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ergo_oracle_pool_box_rate" }
   ]
  },
  {
   "title": "Reward tokens in buyback box",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ergo_oracle_reward_tokens_in_buyback_box"
    }
   ]
  },
  {
   "title": "Active oracle boxes heights",
   "type": "graph",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ergo_oracle_active_oracle_box_height"
    }
   ]
  },
  { "title": "Oracle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Oracle health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ergo_oracle_oracle_is_healthy" }
   ]
  },
  {
   "title": "Node height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ergo_oracle_current_height" }
   ]
  },
  {
   "title": "Pool box, oracle box, node heights",
   "type": "graph",
   "gridPos": { "h": 13, "w": 9, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ergo_oracle_pool_box_height" },
    { "expr": "ergo_oracle_current_height" },
    { "expr": "ergo_oracle_oracle_box_height" }
   ]
  },
  {
   "title": "Nano ERGs in node's wallet",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ergo_oracle_oracle_node_wallet_nano_erg"
    }
   ]
  }
 ]
}